In [1]:
# Answer1.
'''Yes, there is a difference in the data type of list and array_list. The variable list is a Python 
list containing strings, while array_list is a NumPy array containing Unicode strings''' 

import numpy as np

list = ['1', '2', '3', '4', '5']
array_list = np.array(object=list)

print(type(list))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [2]:
# Answer2.
import numpy as np

list = ['1', '2', '3', '4', '5']
array_list = np.array(object=list)

# Print data type of each element in list
for element in list:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [3]:
# Answer3.
''' Yes, there will be a difference in the data type of list and array_list if you change the data
type of the latter to int. The variable list will still be a Python list containing strings, but
array_list will now be a NumPy array containing integers.''' 

import numpy as np

list = ['1', '2', '3', '4', '5']
array_list = np.array(object=list, dtype=int)

# Print data type of each element in list
for element in list:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [4]:
# Answer4.
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find the shape of num_array
shape = num_array.shape
print("Shape of num_array:", shape)

# Find the size of num_array
size = num_array.size
print("Size of num_array:", size)

Shape of num_array: (2, 3)
Size of num_array: 6


In [5]:
# Answer5.
import numpy as np

# Create a 3x3 array of zeros
zeros_array = np.zeros((3, 3))

# Print the array
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Answer6.
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the matrix
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
